# config.yml
pattern:
  date: "dd MMM yy"
  time: "HH:mm:ss"

form:
  text:
    header:
      - "LOGGED DATA"
      - "VER= 2.00"
      - "AUTO DATA                  "
      - "  DATE       TIME     FID BACKGROUND        FID CONCENTRATION  "
      - "---------  --------  --------------------  --------------------"
    footer:
      - "END"
      - "→"